version: '3.9'

services:
  db:
    platform: linux/amd64
    image: peachtree/linkive_database
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  backend:
    platform: linux/amd64
    ports:
      - "80:80"
      - "443:443"
    image: peachtree/linkive_backend
    volumes:
      - ./static:/usr/src/app/static
    restart: always
  web:
    platform: linux/amd64
    image: peachtree/linkive_web
    ports:
      - "80:80"
    restart: always